// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjqvkndjhrcgaymxrrwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcXZrbmRqaHJjZ2F5bXhycndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTk5OTEsImV4cCI6MjA3Mzk5NTk5MX0.ZigPGlpRRvydWMlOx2otuUggAuQ_LTmvtXONRejT0Y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});